FROM centos:8

RUN curl -L -O https://artifacts.elastic.co/downloads/beats/filebeat/filebeat-8.10.3-linux-x86_64.tar.gz \
    && tar xzvf filebeat-8.10.3-linux-x86_64.tar.gz \
    && rm -rf filebeat-8.10.3-linux-x86_64.tar.gz \
    &&