
replicaCount: 1
image:
    repository: qtdocker/hive
    tag: 3.1.3
    pullPolicy: IfNotPresent
service:
    type: None
    portMatedata: 9083
    portHiveserver2: 10000
    portUI: 10002
ingress:
    enabled: false
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
connect:
    hdfs: 
        namenode: my-hadoop-hadoop-hdfs-nn:9000
        path: /hive/warehouse
    mysql:
        server: mysql-svc:3306
        username: hive
        password: Abcde.123
    