apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kafka-chats.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: cmak.shaoyou.store
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "kafka-chats.fullname" . }}-cmak
                port:
                  number: 9000
    - host: kafka.shaoyou.store
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: {{ include "kafka-chats.fullname" . }}
                port:
                  number: 9092

