apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kafka-chats.fullname" . }}
spec:
  ingressClassName: nginx
  rules:
    - host: cmak.shaoyou.store
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: blog-web-svc
                port:
                  number: 80
    - host: kafka.shaoyou.store
      http:
        paths:
          - pathType: Prefix
            path: "/blog"
            backend:
              service:
                name: blog-service-svc
                port:
                  number: 9090
          - pathType: Prefix
            path: "/images"
            backend:
              service:
                name: blog-service-svc
                port:
                  number: 8088

