apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-chats.fullname" . }}-out
  labels:
    app: {{ include "kafka-chats.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 9094
      name: service
      nodePort: 32452
  selector:
    app: {{ include "kafka-chats.fullname" . }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-chats.fullname" . }}-k8s
  labels:
    app: {{ include "kafka-chats.fullname" . }}
spec:
  type: ClusterIP
  ports:
    - port: 9093
      name: service
  selector:
    app: {{ include "kafka-chats.fullname" . }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-chats.fullname" . }}
  labels:
    app: {{ include "kafka-chats.fullname" . }}
spec:
  clusterIP: None
  selector:
    app: {{ include "kafka-chats.fullname" . }}
