apiVersion: v1
kind: Service
metadata:
  name: {{ include "kafka-chats.fullname" . }}
  labels:
    app: {{ include "kafka-chats.fullname" . }}
spec:
  type: NodePort
  ports:
    - port: 9094
      name: service
      nodePort: 32452
  selector:
    app: {{ include "kafka-chats.fullname" . }}
