apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: {{ include "kafka-chats.fullname" . }}
  labels:
    app: {{ include "kafka-chats.fullname" . }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ include "kafka-chats.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ include "kafka-chats.fullname" . }}
    spec:
      containers:
        - name: kafka
          image: qtdocker/kafka:3.5.1_2.12
          imagePullPolicy: IfNotPresent
          volumeMounts:
            - name: server-properties
              mountPath: /usr/local/kafka/config/server.properties
              subPath: server.properties
              readOnly: true
          ports:
            - name: ui
              containerPort: 9000
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: ui
            initialDelaySeconds: 100
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: ui
            initialDelaySeconds: 100
            timeoutSeconds: 5

      volumes:
        - name: server-properties
          configMap:
            name: {{ include "kafka-chats.fullname" . }}

