apiVersion: v1
kind: ConfigMap
metadata:
  name: canal
  labels:
    app: canal
data:
  start.sh: |+
    #!/bin/bash
    set -e
    TMP_URL=canal-admin:8089
    if timeout 5m bash -c "until curl -sf $TMP_URL; do echo Waiting for $TMP_URL; sleep 5; done";
    then
      sh /opt/canal/bin/startup.sh
      sleep 10
      tail -f /opt/canal/logs/canal/canal.log
    else
      echo "$0: Timeout waiting for $TMP_URL, exiting."
      exit 1
    fi

  canal.properties: |+
    # register ip
    canal.register.ip =
    # canal admin config
    canal.admin.manager = canal-admin:8089
    canal.admin.port = 11110
    canal.admin.user = admin
    canal.admin.passwd = 4ACFE3202A5FF5CF467898FC58AAB1D615029441
    # admin auto register
    canal.admin.register.auto = true
    canal.admin.register.cluster = canal-cluster

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: canal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: canal
  template:
    metadata:
      labels:
        app: canal
    spec:
      #添加标签调度
      #nodeSelector:
      #  app1: mysql
      
      #根据 NodeName 调度
      containers:
      - name: canal
        image: qtdocker/canal:1.1.6
        imagePullPolicy: IfNotPresent
        command: ["/bin/sh", "/opt/start.sh"]
        volumeMounts:
        - name: start-sh
          mountPath: /opt/start.sh
          subPath: start.sh
        - name: canal-properties
          mountPath: /opt/canal/conf/canal.properties
          subPath: canal.properties
      volumes:
        - name: start-sh
          configMap:
            name: canal
        - name: canal-properties
          configMap:
            name: canal
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: canal
  labels:
    app: canal
spec:
  ports:
  - port: 11111
    name: canal1
    targetPort: 11111
  - port: 11110
    name: canal0
    targetPort: 11110
  selector:
    app: canal

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: canal
spec:
  ingressClassName: nginx
  rules:
    - host: canal.shaoyou.store
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: canal
                port:
                  number: 11111
