apiVersion: apps/v1
kind: Deployment
metadata:
  name: blog-web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: blog-web-pod
  template:
    metadata:
      labels:
        app: blog-web-pod
    spec:
      containers:
        - name: blog-web-app
          image: registry.cn-hangzhou.aliyuncs.com/qt1/blog_web:1.0.0
          imagePullPolicy: Always
          command: ['bash', '-c', "cd /root/code/sy_blog && git pull && npm install && npm run-script build && nginx -g 'daemon off;'"]
      imagePullSecrets:
        - name: self-registry

