apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hive-ingress
spec:
  ingressClassName: nginx
  rules:
    - host: hive.shaoyou.store
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hive-hiveserver-ui
                port:
                  number: 10002
    - host: hiveservice2.shaoyou.store
      http:
        paths:
          - pathType: Prefix
            path: "/"
            backend:
              service:
                name: hive-hiveserver-hiveserver2
                port:
                  number: 10000