apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-metastore
  labels:
    app: {{ include "hive.name" . }}
    chart: {{ include "hive.chart" . }}
    release: {{ .Release.Name }}
spec:
  clusterIP: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portMatedata }}
      targetPort: metastore
      protocol: TCP
      name: metastore
  selector:
    app: {{ include "hive.name" . }}
    release: {{ .Release.Name }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-ui
  labels:
    app: {{ include "hive.name" . }}
    chart: {{ include "hive.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.portUI }}
      targetPort: ui
      protocol: TCP
      name: ui
  selector:
    app: {{ include "hive.name" . }}
    release: {{ .Release.Name }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "hive.fullname" . }}-hiveserver2
  labels:
    app: {{ include "hive.name" . }}
    chart: {{ include "hive.chart" . }}
    release: {{ .Release.Name }}
spec:
  ports:
    - port: {{ .Values.service.portHiveserver2 }}
      targetPort: hiveserver2
      protocol: TCP
      name: hiveserver2
  selector:
    app: {{ include "hive.name" . }}
    release: {{ .Release.Name }}