apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: hadoop-read-pvc
spec:
  storageClassName: 'hadoop-read-pv'
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem