apiVersion: v1
kind: PersistentVolume
metadata:
  name: mvn-repo-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: 'mvn-repo-pvc'
  local:
    path: /opt/.m2/repository
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1