apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zeppelin-read-pv
spec:
  storageClassName: 'zeppelin-read-pv'
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem