apiVersion: v1
kind: PersistentVolume
metadata:
  name: zeppelin-read-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
  - ReadOnlyMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: 'zeppelin-read-pv'
  local:
    path: /opt/zeppelin
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - node1